name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.136.5'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Hugo
      run: |
        wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.WC_HUGO_VERSION }}/hugo_extended_${{ env.WC_HUGO_VERSION }}_linux-amd64.tar.gz
        tar -xzf hugo_extended_${{ env.WC_HUGO_VERSION }}_linux-amd64.tar.gz
        sudo mv hugo /usr/local/bin/
        rm hugo_extended_${{ env.WC_HUGO_VERSION }}_linux-amd64.tar.gz

    - name: Cache Hugo modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/hugo
          $(hugo config | grep cachedir | awk '{print $3}')
        key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-hugo-

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4

    - name: Build with Hugo
      env:
        HUGO_ENVIRONMENT: production
      run: |
        hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

    - name: Generate Pagefind search index
      run: npx pagefind --site "public"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public

  deploy:
    if: github.repository_owner != 'HugoBlox'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3