name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.2'

    - name: Cache Hugo modules
      uses: actions/cache@v3
      with:
        path: | 
          ~/.cache/hugo
          ~/.hugo_build.lock
        key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugo-

    - name: Build
      run: hugo --minify

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: hugo-site
        path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-pages-artifact@v1
      with:
        name: hugo-site
        path: public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public